ALTER TABLE blogs ADD COLUMN info text;
ALTER TABLE blogs RENAME TO blog;
ALTER TABLE blog DROP COLUMN capabilities;
DELETE FROM qso WHERE type='cmd' OR type='progress' OR type='post';
DELETE FROM qso WHERE rowid NOT IN (select FIRST_VALUE(rowid) OVER (PARTITION BY blog, post_id ORDER BY blog, post_id, post_date DESC) FROM qso);
DELETE FROM qso WHERE hex(title) LIKE '%E280%';
DELETE FROM qso WHERE post_id = 0;
DELETE FROM qso WHERE LENGTH(title) = 0;
DELETE FROM qso WHERE rowid NOT IN (SELECT MIN(rowid) FROM qso GROUP BY post_id);
ALTER TABLE qso RENAME TO post;
ALTER TABLE post DROP COLUMN rsp;
ALTER TABLE post DROP COLUMN type;
ALTER TABLE post ADD COLUMN is_selected integer;
CREATE TABLE progress (qso_date integer, blog text, station text, frequency integer, offset integer, message text);
DELETE FROM settings WHERE name='max_latest';
UPDATE settings SET name = 'max_posts' WHERE name = 'max_qsos';
ALTER TABLE status RENAME COLUMN blogs_updated to blog_updated;
ALTER TABLE status RENAME COLUMN qso_updated TO post_list_updated;
ALTER TABLE status RENAME COLUMN latest_updated to post_updated;
ALTER TABLE status DROP COLUMN req_outstanding;
ALTER TABLE status DROP COLUMN last_checked;
ALTER TABLE status DROP COLUMN hdr_updated;
ALTER TABLE status DROP COLUMN post_updated;
ALTER TABLE status DROP COLUMN post_list_updated;
ALTER TABLE status DROP COLUMN blog_updated;
ALTER TABLE status DROP COLUMN is_scanning;
ALTER TABLE status DROP COLUMN selected_blog;
ALTER TABLE status DROP COLUMN selected_station;
